### ISSUE TITLE
Address static package installation

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/c-blosc2-feedstock#6]
https://github.com/conda-forge/cfep/blob/main/cfep-18.md

@FrancescAlted are you using the static library? if not , is an acceptable fix to just remove the static build? given how new this feedstock is, this might be the lowest maintenance solution.

**Comment by FrancescAlted** [comment]
No, the Blosc team is not making use of the C-Blosc2 libraries in conda-forge, so feel free to get rid of them.

FYI, the Blosc project is actively supporting the inclusion of both the static and dynamic libraries of C-Blosc inside of the python-blosc wheels https://www.blosc.org/posts/new-blosc-wheels/.  In the future, we plan to do the same with C-Blosc2/python-blosc2; at any rate, this is completely ortogonal to conda-forge packaging.

**Comment by hmaarrfk** [comment]
Yes, i believe that pip packaging requires all c dependencies to be in the wheel itself. rather annoying at times. 

ok, i'll remove them from the 2.0.3 build.
