### ISSUE TITLE
Unbundle libraries

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/c-blosc2-feedstock#7]
This package seems to bundle zlib and zstd an lz4
https://github.com/Blosc/c-blosc2/tree/main/internal-complibs

**Comment by hmaarrfk** [comment]
Not sure why zlib Ng is still falling in windows

**Comment by zklaus** [comment]
@hmaarrfk, going through this repo, is it true that this issue together with PRs #9, #10, and #14, is addressed by now?

**Comment by hmaarrfk** [comment]
Not for windows

**Comment by hmaarrfk** [comment]
Sorry for letting them linger for so long.

Some were me testing things out. Others were debugging an actual bug in the original version. I closed them all.

You are correct that we still need to unbundle windows. I figured the accepted PR was a move in the right direction, so I merged it. Your help would be greatly apprecaited. I feel like there is a bug somewhere in my defined constants. Maybe in looking for the library?
